# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grayson Kent
email: grayson@linux.com
description: > # this means to ignore newlines until "baseurl:"
 I am a Linux Systems Engineer specializing in high-availability clustering, KVM virtualization, and managing large datasets. I am have a special interest in virtualized networking appliances, handling large data sets for Machine Learning, and robotics. This blog is my way to give back for all the help I have received over the years and documents some of my mistakes so others can learn from it. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://graysonskent.com" # the base hostname & protocol for your site
twitter_username: graysonkent
github_username:  graysonkent

# Build settings
markdown: kramdown
