# General Settings
name: Grayson Kent
author: Grayson Kent
title: Grayson Kent
logo: /assets/images/branch.png
url: https://grayson.sh
job_title: Linux Systems Engineer
email: grayson@linux.com
description:  Grayson Kent's blog focusing on Linux, Networking, Security, Virtualization
avatar: /assets/images/face.jpg
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title

# Social Accounts for SEO tags
social:
name: Grayson Kent
links:
  - https://www.linkedin.com/in/graysonkent
  - https://github.com/graysonkent
  - http://stackexchange.com/users/8499248/grayson-kent?tab=accounts

# Webmaster verifications
webmaster_verifications:
  google: 2b2yT0SglsoaAwDhn8EZ6nM6DRWdlvjpYcJuPfFC8iE

# Modules Settings
show_menu: 1
fixed_sidebar: 1

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from

# Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/branch.png